#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the FirstBitcoinCapitalCorp network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */

//bitTODO - add addresses
static SeedSpec6 pnSeed6_main[] = {
//    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x47,0xbf,0x54,0x11}, 16661}
};

static SeedSpec6 pnSeed6_test[] = {
//    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0xbc,0xa6,0x0b,0xe9}, 16663}
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
